name: Ejecutor Centinela Watchdog

on:
  schedule:
    - cron: '0 */6 * * *' # Ejecuta automáticamente cada 6 horas
  workflow_dispatch: # Botón manual "Run workflow" en la pestaña Actions

jobs:
  centinela-check:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar Código del Repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js Runtime
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ejecutar Script Centinela
        env:
          FIREBASE_DB_URL: "https://bolsa-de-trabajo-a52e4-default-rtdb.firebaseio.com"
          FIREBASE_SECRET: ${{ secrets.FIREBASE_DB_SECRET }}
        run: node .github/workflows/script-centinela.js
